const Map<String, List<String>> campusHostels = {
  'nit-kkr': [
    'H1',
    'H2',
    'H3',
    'H4',
    'H5',
    'H6',
    'H7',
    'H8',
    'H9',
    'H10',
    'H11',
    'G1',
    'G2',
    'G3',
  ],
  'iit-bhu': [
    'Aryabhatta Hostel',
    'S. N. Bose Hostel',
    'C. V. Raman Hostel',
    'Dhanrajgiri Hostel',
    'Satish Dhawan Hostel',
    'S. Ramanujan Hostel',
    'GSMC Old & Extension Hostel',
    'Nivedita Girls Hostel',
    'S. S. Saluja Hostel',
    'Morvi Hostel',
    'Rajputana Hostel',
    'Limbdi Hostel',
    'Vishwakarma Hostel',
    'S. C. De Girls Hostel',
    'Vishweshwaraiya Hostel',
    'Vivekananda Hostel',
    'Prafulla Chandra Ray Hostel',
  ],
};
